#!/bin/bash

# 🚀 ShareLink Complete Deployment Guide
echo "==============================================="
echo "🚀 ShareLink - Complete Deployment Guide"
echo "==============================================="

echo "📧 Newsletter Email Management:"
echo "--------------------------------"
echo "✅ Email data is stored in: backend/data/newsletter.json"
echo "✅ Admin Panel: http://your-domain.com/newsletter-admin.html"
echo "✅ Export CSV: curl 'http://your-domain.com/api/newsletter/export?format=csv'"
echo "✅ Export JSON: curl 'http://your-domain.com/api/newsletter/export?format=json'"
echo ""

echo "🚀 Deployment Options:"
echo "----------------------"
echo "1. Local Development:"
echo "   cd backend && npm start (Port 5001)"
echo "   cd frontend && npm start (Port 3001)"
echo ""
echo "2. Docker Compose (Recommended):"
echo "   ./deploy.sh"
echo ""
echo "3. Manual Docker:"
echo "   docker build -t sharelink-backend ./backend"
echo "   docker build -t sharelink-frontend ./frontend"
echo "   docker-compose up -d"
echo ""

echo "☁️ Cloud Deployment Options:"
echo "----------------------------"
echo "1. Heroku:"
echo "   - Create two apps: sharelink-backend, sharelink-frontend"
echo "   - Deploy backend and frontend separately"
echo "   - Set environment variables"
echo ""
echo "2. Vercel (Frontend) + Railway/Render (Backend):"
echo "   - Deploy frontend to Vercel"
echo "   - Deploy backend to Railway/Render"
echo "   - Update API_BASE in frontend"
echo ""
echo "3. DigitalOcean App Platform:"
echo "   - Connect GitHub repository"
echo "   - Configure build settings"
echo "   - Set environment variables"
echo ""
echo "4. AWS ECS:"
echo "   - Use provided Dockerfiles"
echo "   - Configure load balancer"
echo "   - Set up health checks"
echo ""

echo "🔧 Environment Configuration:"
echo "-----------------------------"
echo "Create .env file with:"
echo "NODE_ENV=production"
echo "API_BASE=https://your-domain.com/api"
echo "CORS_ORIGIN=https://your-domain.com"
echo "MAX_FILE_SIZE=500MB"
echo "MAX_FILES=10"
echo ""

echo "📊 Health Checks:"
echo "-----------------"
echo "Frontend: http://your-domain.com/health"
echo "Backend: http://your-domain.com/api/health"
echo "Newsletter: http://your-domain.com/api/newsletter/health"
echo ""

echo "📧 Newsletter Management:"
echo "------------------------"
echo "- Access admin panel at /newsletter-admin.html"
echo "- Export subscriber lists in CSV/JSON formats"
echo "- View real-time analytics and statistics"
echo "- Email data stored in backend/data/newsletter.json"
echo ""

echo "🛡️ Security Features:"
echo "---------------------"
echo "✅ Rate limiting on API endpoints"
echo "✅ File type validation"
echo "✅ PIN protection for shares"
echo "✅ Auto-expiry for links"
echo "✅ CORS protection"
echo "✅ Security headers"
echo ""

echo "🔗 Key URLs:"
echo "------------"
echo "Main App: http://your-domain.com"
echo "Newsletter Admin: http://your-domain.com/newsletter-admin.html"
echo "API Docs: http://your-domain.com/api/health"
echo ""

echo "✅ ShareLink is now ready for deployment!"
echo "📧 Email data will be collected automatically"
echo "🚀 Choose your preferred deployment method above"
echo "==============================================="
